/**
 * @module types
 * Core type definitions and constants for the Wildgate Stat Tracker.
 * Re-exports constants from utils/constants.ts for convenience.
 */

/** The two competitive game modes available in Wildgate. */
export type GameMode = 'Artifact Brawl' | 'Fleet Battle';
/** Possible outcomes for a completed match. */
export type MatchResult = 'Win' | 'Loss' | 'Draw';
/** Supported colorblind filter modes, applied via SVG filters in index.html. */
export type ColorblindMode = 'none' | 'protanopia' | 'deuteranopia' | 'tritanopia';

export * from './utils/constants';

/** Supported UI languages. Translations live in utils/translations.ts. */
export type Language = 'en' | 'es' | 'mx' | 'pt' | 'br' | 'zh';

/** Maps ship type names to kill counts for a single match. */
export interface KillMap {
  [shipName: string]: number;
}

/** A player's equipped loadout detected from telemetry or OCR. */
export interface Loadout {
  hero: string | null;
  ship: string | null;
  weapons: string[];
  equipment: string[];
}

/** Primary data record for a completed match. Persisted to disk via StorageService. */
export interface Match {
  id: number;
  timestamp: number;
  date: string;
  mode: GameMode;
  player: string;
  teammates: string[];
  opponents: string[];
  hero: string;
  ship: string;
  loadout?: Loadout; // New field
  weapons?: Record<string, number>; // Legacy/Usage stats
  reachModifiers: string[];
  kills: KillMap;
  result: 'Win' | 'Loss' | 'Draw';
  subType: string;
  placement?: number;
  damageTaken?: number;
  time?: string;
  poiEasy?: number;
  poiMedium?: number;
  poiEpic?: number;
  artifactSource?: string;
  killedBy?: string;
  isPinned?: boolean;
  notes?: string;
  timelineEvents?: any[]; // New field for match chronology
  artifacts?: string[]; // New field for bundled screenshots
}

/** Returns crew capacity (1-4) based on the ship display name. */
export const getShipCapacity = (ship: string): number => {
  if (ship.includes("4 Player")) return 4;
  if (ship.includes("3 Player")) return 3;
  if (ship.includes("2 Player")) return 2;
  return 1;
};

/** Returns a hex color associated with the ship class for chart rendering. */
export const getShipColor = (ship: string): string => {
  if (ship.includes("Hunter")) return "#ef4444";
  if (ship.includes("Bastion")) return "#3b82f6";
  if (ship.includes("Privateer")) return "#eab308";
  if (ship.includes("Scout")) return "#22c55e";
  return "#a855f7";
};

/** Target for the analytics drill-down overlay — clicking a chart element sets this. */
export type DrillDownTarget = { type: 'Ship' | 'Hero' | 'Teammate' | 'Opponent' | 'Artifact' | 'KPI', name: string };

/** A computed analytics insight card shown on the dashboard. Generated by analytics.ts. */
export interface Insight {
  title: string;
  subtitle: string;
  value: string;
  subValue: string;
  color: string;
  iconType: 'Rocket' | 'Crown' | 'Flame' | 'Zap' | 'Clock' | 'Target' | 'ShieldCheck' | 'Ghost' | 'Crosshair' | 'Moon' | 'Sun' | 'Users' | 'User' | 'Mountain' | 'Skull' | 'AlertTriangle';
  priority: number;
}